In [37]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [38]:
import pandas as pd

In [39]:
df=pd.read_csv("/content/zepto_dirty_400.csv")
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19.0,NaN,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53.0,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58.0,45.26,8.0,23.0,Wallet,5.0,NaN
3,ZPT2003,Snacks,Mumbai,27.0,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58.0,2457.07,10.0,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43.0,1049.62,12.0,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51.0,1301.64,6.0,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44.0,889.32,6.0,44.0,UPI,3.0,NaN
418,ZPT2418,Bakery,Mumbai,42.0,811.62,8.0,28.0,Cash,3.0,NaN
419,ZPT2419,Meat & Fish,Mumbai,51.0,2076.81,3.0,44.0,Wallet,2.0,NaN

In [40]:
df.shape

(420, 10)

In [41]:
df.head()

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19.0,NaN,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53.0,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58.0,45.26,8.0,23.0,Wallet,5.0,NaN
3,ZPT2003,Snacks,Mumbai,27.0,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58.0,2457.07,10.0,25.0,UPI,1.0,Cancelled

In [42]:
df.dtypes

Order_ID               object
Category               object
City                   object
Customer_Age          float64
Price                 float64
Quantity              float64
Delivery_Time_mins    float64
Payment_Method         object
Rating                float64
Order_Status           object
dtype: object

In [43]:
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            420 non-null    object
 1   Category            420 non-null    object
 2   City                318 non-null    object
 3   Customer_Age        405 non-null    float64
 4   Price               408 non-null    float64
 5   Quantity            410 non-null    float64
 6   Delivery_Time_mins  410 non-null    float64
 7   Payment_Method      309 non-null    object
 8   Rating              390 non-null    float64
 9   Order_Status        281 non-null    object
dtypes: float64(5), object(5)
memory usage: 32.9+ KB

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19.0,NaN,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53.0,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58.0,45.26,8.0,23.0,Wallet,5.0,NaN
3,ZPT2003,Snacks,Mumbai,27.0,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58.0,2457.07,10.0,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43.0,1049.62,12.0,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51.0,1301.64,6.0,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44.0,889.32,6.0,44.0,UPI,3.0,NaN
418,ZPT2418,Bakery,Mumbai,42.0,811.62,8.0,28.0,Cash,3.0,NaN
419,ZPT2419,Meat & Fish,Mumbai,51.0,2076.81,3.0,44.0,Wallet,2.0,NaN

In [44]:
df.describe()

       Customer_Age        Price    Quantity  Delivery_Time_mins      Rating
count    405.000000   408.000000  410.000000          410.000000  390.000000
mean      41.518519  1283.207868    7.378049           31.285366    3.010256
std       13.821986   716.040062    3.876581           51.228612    1.451848
min       18.000000    36.480000    1.000000          -10.000000    0.000000
25%       29.000000   649.202500    4.000000           18.000000    2.000000
50%       43.000000  1263.985000    7.000000           29.000000    3.000000
75%       53.000000  1942.507500   10.000000           39.000000    4.000000
max       64.000000  2485.750000   14.000000          999.000000    7.000000

In [45]:
df.isnull().sum()

Order_ID                0
Category                0
City                  102
Customer_Age           15
Price                  12
Quantity               10
Delivery_Time_mins     10
Payment_Method        111
Rating                 30
Order_Status          139
dtype: int64

In [46]:
df.isnull().sum().sum()

np.int64(429)

In [47]:
df.isnull().mean()*100

Order_ID               0.000000
Category               0.000000
City                  24.285714
Customer_Age           3.571429
Price                  2.857143
Quantity               2.380952
Delivery_Time_mins     2.380952
Payment_Method        26.428571
Rating                 7.142857
Order_Status          33.095238
dtype: float64

In [48]:
df.duplicated().sum()
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19.0,NaN,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53.0,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58.0,45.26,8.0,23.0,Wallet,5.0,NaN
3,ZPT2003,Snacks,Mumbai,27.0,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58.0,2457.07,10.0,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43.0,1049.62,12.0,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51.0,1301.64,6.0,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44.0,889.32,6.0,44.0,UPI,3.0,NaN
418,ZPT2418,Bakery,Mumbai,42.0,811.62,8.0,28.0,Cash,3.0,NaN
419,ZPT2419,Meat & Fish,Mumbai,51.0,2076.81,3.0,44.0,Wallet,2.0,NaN

In [49]:
df.duplicated(subset='Order_ID').sum()

np.int64(5)

In [50]:
df[df.duplicated(subset='Order_ID',keep=False)]

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
10,ZPT2010,fruits & vegetables,Chennai,53.0,2057.98,3.0,10.0,UPI,3.0,NaN
20,ZPT2010,Bakery,NaN,26.0,1514.54,5.0,11.0,NaN,2.0,NaN
45,ZPT2045,Dairy & Eggs,Ahmedabad,29.0,451.33,5.0,19.0,Debit Card,2.0,Delivered
55,ZPT2045,Meat & Fish,Hyderabad,58.0,634.86,12.0,39.0,Wallet,1.0,Pending
100,ZPT2100,Bakery,NaN,59.0,1451.53,1.0,16.0,NaN,3.0,Returned
110,ZPT2100,Snacks,NaN,18.0,167.39,7.0,8.0,Wallet,NaN,NaN
190,ZPT2190,Meat & Fish,Chennai,34.0,54.80,1.0,29.0,NaN,2.0,NaN
200,ZPT2190,Cleaning,Kolkata,36.0,1429.99,5.0,38.0,NaN,0.0,NaN
300,ZPT2300,Bakery,Chennai,39.0,2180.72,4.0,-3.0,Cash,5.0,Returned
310,ZPT2300,Meat & Fish,NaN,51.0,2063.11,10.0,49.0,NaN,NaN,NaN

In [51]:
df=df.drop_duplicates(subset='Order_ID',keep='first')
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19.0,NaN,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53.0,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58.0,45.26,8.0,23.0,Wallet,5.0,NaN
3,ZPT2003,Snacks,Mumbai,27.0,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58.0,2457.07,10.0,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43.0,1049.62,12.0,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51.0,1301.64,6.0,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44.0,889.32,6.0,44.0,UPI,3.0,NaN
418,ZPT2418,Bakery,Mumbai,42.0,811.62,8.0,28.0,Cash,3.0,NaN
419,ZPT2419,Meat & Fish,Mumbai,51.0,2076.81,3.0,44.0,Wallet,2.0,NaN

In [53]:
num_cols=['Customer_Age','Price','Quantity','Delivery_Time_mins','Rating']
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19.0,NaN,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53.0,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58.0,45.26,8.0,23.0,Wallet,5.0,NaN
3,ZPT2003,Snacks,Mumbai,27.0,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58.0,2457.07,10.0,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43.0,1049.62,12.0,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51.0,1301.64,6.0,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44.0,889.32,6.0,44.0,UPI,3.0,NaN
418,ZPT2418,Bakery,Mumbai,42.0,811.62,8.0,28.0,Cash,3.0,NaN
419,ZPT2419,Meat & Fish,Mumbai,51.0,2076.81,3.0,44.0,Wallet,2.0,NaN

In [55]:
for col in num_cols:
  df[col]=df[col].fillna(df[col].median())

/tmp/ipykernel_256/2865236840.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col]=df[col].fillna(df[col].median())

In [57]:
cat_cols=['City','Payment_Method','Order_Status']
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19.0,1262.81,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53.0,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58.0,45.26,8.0,23.0,Wallet,5.0,NaN
3,ZPT2003,Snacks,Mumbai,27.0,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58.0,2457.07,10.0,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43.0,1049.62,12.0,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51.0,1301.64,6.0,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44.0,889.32,6.0,44.0,UPI,3.0,NaN
418,ZPT2418,Bakery,Mumbai,42.0,811.62,8.0,28.0,Cash,3.0,NaN
419,ZPT2419,Meat & Fish,Mumbai,51.0,2076.81,3.0,44.0,Wallet,2.0,NaN

In [58]:
for col in cat_cols:
  df[col]=df[col].fillna(df[col].mode()[0])

/tmp/ipykernel_256/1979246709.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col]=df[col].fillna(df[col].mode()[0])

In [59]:
df['Category'].unique()

array(['Personal Care', 'Dairy & Eggs', 'Bakery', 'Snacks', 'Beverages',
       'Cleaning', 'fruits & vegetables', 'Meat & Fish',
       'Fruits & Vegetables', 'SNACKS', ' Dairy & Eggs ', 'beverages',
       'CLEANING', 'personal care', 'meat & fish', ' Bakery '],
      dtype=object)

In [60]:
df['Category']=df['Category'].str.strip()

/tmp/ipykernel_256/1835876973.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category']=df['Category'].str.strip()

In [61]:
df['Category']=df['Category'].str.title()

/tmp/ipykernel_256/2306666527.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category']=df['Category'].str.title()

In [62]:
df['Category']=df['Category'].str.strip().str.title()

/tmp/ipykernel_256/1024207571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category']=df['Category'].str.strip().str.title()

In [64]:
df['Delivery_Time_mins'].describe()

count    415.000000
mean      31.257831
std       50.886997
min      -10.000000
25%       18.000000
50%       29.000000
75%       38.000000
max      999.000000
Name: Delivery_Time_mins, dtype: float64

In [66]:
df=df[(df['Delivery_Time_mins']>=0)&(df['Delivery_Time_mins']<=60)]
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19.0,1262.81,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53.0,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58.0,45.26,8.0,23.0,Wallet,5.0,Returned
3,ZPT2003,Snacks,Mumbai,27.0,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58.0,2457.07,10.0,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43.0,1049.62,12.0,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51.0,1301.64,6.0,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44.0,889.32,6.0,44.0,UPI,3.0,Returned
418,ZPT2418,Bakery,Mumbai,42.0,811.62,8.0,28.0,Cash,3.0,Returned
419,ZPT2419,Meat & Fish,Mumbai,51.0,2076.81,3.0,44.0,Wallet,2.0,Returned

In [68]:
df=df[(df['Rating']>=1)&(df['Rating']<=5)]
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19.0,1262.81,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53.0,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58.0,45.26,8.0,23.0,Wallet,5.0,Returned
3,ZPT2003,Snacks,Mumbai,27.0,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58.0,2457.07,10.0,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43.0,1049.62,12.0,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51.0,1301.64,6.0,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44.0,889.32,6.0,44.0,UPI,3.0,Returned
418,ZPT2418,Bakery,Mumbai,42.0,811.62,8.0,28.0,Cash,3.0,Returned
419,ZPT2419,Meat & Fish,Mumbai,51.0,2076.81,3.0,44.0,Wallet,2.0,Returned

In [69]:
df.dtypes

Order_ID               object
Category               object
City                   object
Customer_Age          float64
Price                 float64
Quantity              float64
Delivery_Time_mins    float64
Payment_Method         object
Rating                float64
Order_Status           object
dtype: object

In [71]:
df['Customer_Age']=df['Customer_Age'].astype('int64')
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19,1262.81,8.0,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53,2126.57,8.0,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58,45.26,8.0,23.0,Wallet,5.0,Returned
3,ZPT2003,Snacks,Mumbai,27,1771.35,7.0,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58,2457.07,10.0,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43,1049.62,12.0,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51,1301.64,6.0,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44,889.32,6.0,44.0,UPI,3.0,Returned
418,ZPT2418,Bakery,Mumbai,42,811.62,8.0,28.0,Cash,3.0,Returned
419,ZPT2419,Meat & Fish,Mumbai,51,2076.81,3.0,44.0,Wallet,2.0,Returned

In [73]:
df['Quantity']=df['Quantity'].astype('int64')
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19,1262.81,8,26.0,Debit Card,3.0,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53,2126.57,8,17.0,UPI,2.0,Returned
2,ZPT2002,Bakery,Ahmedabad,58,45.26,8,23.0,Wallet,5.0,Returned
3,ZPT2003,Snacks,Mumbai,27,1771.35,7,23.0,Wallet,4.0,Pending
4,ZPT2004,Beverages,Pune,58,2457.07,10,25.0,UPI,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43,1049.62,12,39.0,Debit Card,4.0,Delivered
416,ZPT2416,Cleaning,Hyderabad,51,1301.64,6,44.0,Wallet,5.0,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44,889.32,6,44.0,UPI,3.0,Returned
418,ZPT2418,Bakery,Mumbai,42,811.62,8,28.0,Cash,3.0,Returned
419,ZPT2419,Meat & Fish,Mumbai,51,2076.81,3,44.0,Wallet,2.0,Returned

In [75]:
df['Rating']=df['Rating'].astype('int64')
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status
0,ZPT2000,Personal Care,Pune,19,1262.81,8,26.0,Debit Card,3,Delivered
1,ZPT2001,Dairy & Eggs,Mumbai,53,2126.57,8,17.0,UPI,2,Returned
2,ZPT2002,Bakery,Ahmedabad,58,45.26,8,23.0,Wallet,5,Returned
3,ZPT2003,Snacks,Mumbai,27,1771.35,7,23.0,Wallet,4,Pending
4,ZPT2004,Beverages,Pune,58,2457.07,10,25.0,UPI,1,Cancelled
...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43,1049.62,12,39.0,Debit Card,4,Delivered
416,ZPT2416,Cleaning,Hyderabad,51,1301.64,6,44.0,Wallet,5,Delivered
417,ZPT2417,Dairy & Eggs,Chennai,44,889.32,6,44.0,UPI,3,Returned
418,ZPT2418,Bakery,Mumbai,42,811.62,8,28.0,Cash,3,Returned
419,ZPT2419,Meat & Fish,Mumbai,51,2076.81,3,44.0,Wallet,2,Returned

In [77]:
df['Total_Amount']=df['Price']*df['Quantity']
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status,Total_Amount
0,ZPT2000,Personal Care,Pune,19,1262.81,8,26.0,Debit Card,3,Delivered,10102.48
1,ZPT2001,Dairy & Eggs,Mumbai,53,2126.57,8,17.0,UPI,2,Returned,17012.56
2,ZPT2002,Bakery,Ahmedabad,58,45.26,8,23.0,Wallet,5,Returned,362.08
3,ZPT2003,Snacks,Mumbai,27,1771.35,7,23.0,Wallet,4,Pending,12399.45
4,ZPT2004,Beverages,Pune,58,2457.07,10,25.0,UPI,1,Cancelled,24570.70
...,...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43,1049.62,12,39.0,Debit Card,4,Delivered,12595.44
416,ZPT2416,Cleaning,Hyderabad,51,1301.64,6,44.0,Wallet,5,Delivered,7809.84
417,ZPT2417,Dairy & Eggs,Chennai,44,889.32,6,44.0,UPI,3,Returned,5335.92
418,ZPT2418,Bakery,Mumbai,42,811.62,8,28.0,Cash,3,Returned,6492.96
419,ZPT2419,Meat & Fish,Mumbai,51,2076.81,3,44.0,Wallet,2,Returned,6230.43

In [78]:
df[['Order_ID','Price','Quantity','Total_Amount']].head()
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status,Total_Amount
0,ZPT2000,Personal Care,Pune,19,1262.81,8,26.0,Debit Card,3,Delivered,10102.48
1,ZPT2001,Dairy & Eggs,Mumbai,53,2126.57,8,17.0,UPI,2,Returned,17012.56
2,ZPT2002,Bakery,Ahmedabad,58,45.26,8,23.0,Wallet,5,Returned,362.08
3,ZPT2003,Snacks,Mumbai,27,1771.35,7,23.0,Wallet,4,Pending,12399.45
4,ZPT2004,Beverages,Pune,58,2457.07,10,25.0,UPI,1,Cancelled,24570.70
...,...,...,...,...,...,...,...,...,...,...,...
415,ZPT2415,Personal Care,Kolkata,43,1049.62,12,39.0,Debit Card,4,Delivered,12595.44
416,ZPT2416,Cleaning,Hyderabad,51,1301.64,6,44.0,Wallet,5,Delivered,7809.84
417,ZPT2417,Dairy & Eggs,Chennai,44,889.32,6,44.0,UPI,3,Returned,5335.92
418,ZPT2418,Bakery,Mumbai,42,811.62,8,28.0,Cash,3,Returned,6492.96
419,ZPT2419,Meat & Fish,Mumbai,51,2076.81,3,44.0,Wallet,2,Returned,6230.43

In [79]:
df=df.reset_index(drop=True)
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status,Total_Amount
0,ZPT2000,Personal Care,Pune,19,1262.81,8,26.0,Debit Card,3,Delivered,10102.48
1,ZPT2001,Dairy & Eggs,Mumbai,53,2126.57,8,17.0,UPI,2,Returned,17012.56
2,ZPT2002,Bakery,Ahmedabad,58,45.26,8,23.0,Wallet,5,Returned,362.08
3,ZPT2003,Snacks,Mumbai,27,1771.35,7,23.0,Wallet,4,Pending,12399.45
4,ZPT2004,Beverages,Pune,58,2457.07,10,25.0,UPI,1,Cancelled,24570.70
...,...,...,...,...,...,...,...,...,...,...,...
405,ZPT2415,Personal Care,Kolkata,43,1049.62,12,39.0,Debit Card,4,Delivered,12595.44
406,ZPT2416,Cleaning,Hyderabad,51,1301.64,6,44.0,Wallet,5,Delivered,7809.84
407,ZPT2417,Dairy & Eggs,Chennai,44,889.32,6,44.0,UPI,3,Returned,5335.92
408,ZPT2418,Bakery,Mumbai,42,811.62,8,28.0,Cash,3,Returned,6492.96
409,ZPT2419,Meat & Fish,Mumbai,51,2076.81,3,44.0,Wallet,2,Returned,6230.43

In [80]:
print(df.shape)
df

(410, 11)

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status,Total_Amount
0,ZPT2000,Personal Care,Pune,19,1262.81,8,26.0,Debit Card,3,Delivered,10102.48
1,ZPT2001,Dairy & Eggs,Mumbai,53,2126.57,8,17.0,UPI,2,Returned,17012.56
2,ZPT2002,Bakery,Ahmedabad,58,45.26,8,23.0,Wallet,5,Returned,362.08
3,ZPT2003,Snacks,Mumbai,27,1771.35,7,23.0,Wallet,4,Pending,12399.45
4,ZPT2004,Beverages,Pune,58,2457.07,10,25.0,UPI,1,Cancelled,24570.70
...,...,...,...,...,...,...,...,...,...,...,...
405,ZPT2415,Personal Care,Kolkata,43,1049.62,12,39.0,Debit Card,4,Delivered,12595.44
406,ZPT2416,Cleaning,Hyderabad,51,1301.64,6,44.0,Wallet,5,Delivered,7809.84
407,ZPT2417,Dairy & Eggs,Chennai,44,889.32,6,44.0,UPI,3,Returned,5335.92
408,ZPT2418,Bakery,Mumbai,42,811.62,8,28.0,Cash,3,Returned,6492.96
409,ZPT2419,Meat & Fish,Mumbai,51,2076.81,3,44.0,Wallet,2,Returned,6230.43

In [81]:
print(df.isnull().sum())
df

Order_ID              0
Category              0
City                  0
Customer_Age          0
Price                 0
Quantity              0
Delivery_Time_mins    0
Payment_Method        0
Rating                0
Order_Status          0
Total_Amount          0
dtype: int64

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status,Total_Amount
0,ZPT2000,Personal Care,Pune,19,1262.81,8,26.0,Debit Card,3,Delivered,10102.48
1,ZPT2001,Dairy & Eggs,Mumbai,53,2126.57,8,17.0,UPI,2,Returned,17012.56
2,ZPT2002,Bakery,Ahmedabad,58,45.26,8,23.0,Wallet,5,Returned,362.08
3,ZPT2003,Snacks,Mumbai,27,1771.35,7,23.0,Wallet,4,Pending,12399.45
4,ZPT2004,Beverages,Pune,58,2457.07,10,25.0,UPI,1,Cancelled,24570.70
...,...,...,...,...,...,...,...,...,...,...,...
405,ZPT2415,Personal Care,Kolkata,43,1049.62,12,39.0,Debit Card,4,Delivered,12595.44
406,ZPT2416,Cleaning,Hyderabad,51,1301.64,6,44.0,Wallet,5,Delivered,7809.84
407,ZPT2417,Dairy & Eggs,Chennai,44,889.32,6,44.0,UPI,3,Returned,5335.92
408,ZPT2418,Bakery,Mumbai,42,811.62,8,28.0,Cash,3,Returned,6492.96
409,ZPT2419,Meat & Fish,Mumbai,51,2076.81,3,44.0,Wallet,2,Returned,6230.43

In [83]:
df.to_csv('Zepto_cleaned.csv',index=False)
df

,Order_ID,Category,City,Customer_Age,Price,Quantity,Delivery_Time_mins,Payment_Method,Rating,Order_Status,Total_Amount
0,ZPT2000,Personal Care,Pune,19,1262.81,8,26.0,Debit Card,3,Delivered,10102.48
1,ZPT2001,Dairy & Eggs,Mumbai,53,2126.57,8,17.0,UPI,2,Returned,17012.56
2,ZPT2002,Bakery,Ahmedabad,58,45.26,8,23.0,Wallet,5,Returned,362.08
3,ZPT2003,Snacks,Mumbai,27,1771.35,7,23.0,Wallet,4,Pending,12399.45
4,ZPT2004,Beverages,Pune,58,2457.07,10,25.0,UPI,1,Cancelled,24570.70
...,...,...,...,...,...,...,...,...,...,...,...
405,ZPT2415,Personal Care,Kolkata,43,1049.62,12,39.0,Debit Card,4,Delivered,12595.44
406,ZPT2416,Cleaning,Hyderabad,51,1301.64,6,44.0,Wallet,5,Delivered,7809.84
407,ZPT2417,Dairy & Eggs,Chennai,44,889.32,6,44.0,UPI,3,Returned,5335.92
408,ZPT2418,Bakery,Mumbai,42,811.62,8,28.0,Cash,3,Returned,6492.96
409,ZPT2419,Meat & Fish,Mumbai,51,2076.81,3,44.0,Wallet,2,Returned,6230.43